### PR TITLE
Style order index and show pages

### PR DESCRIPTION
**Pull request by martensonbj**
I added some style to the orders show and index pages. I also pulled the show page code out into a partial called _order_card.html.erb which is in the orders views folder, but I had issues making the variables translate  to the orders_index page.

Additional issues we should address: Something is going on with the cart.rb file when calculating the subtotal of individual items. On both the index and show pages if I add certain pictures I'm getting nil back for the inject method. Germany, Shanghai, Aurora, and Darkness seem to be safe. 

I also think we should add a "delete order" button on the orders index page, or set up a catch method for if the cart is empty -  it's letting me create orders with nothing in them when I click "checkout".

### CODE REVIEW

**Comment by ToniRib** [comment]
@martensonbj pushed up a new commit, I think it fixes both the problem with the partial (and making sure it gets the correct variable) as well as the issue with the subtotals.

**Comment by ToniRib** [comment]
@martensonbj pushed up a new commit, I think it fixes both the problem with the partial (and making sure it gets the correct variable) as well as the issue with the subtotals.

**Comment by ToniRib** [comment]
Also I'm going to write a test for 'user cannot checkout with empty cart' and try to fix that.

**Comment by ToniRib** [comment]
@martensonbj I think I fixed all of the issues you mentioned, so let me know if you agree with the changes before merging it in.

**Comment by ToniRib** [comment]
This should:
closes #41 
closes #44 
closes #40

**Comment by ToniRib** [comment]
Merged in the latest master branch, all tests still passing on this branch.

**Comment by ToniRib** [comment]
Made item show page responsive, closes #59

**Comment by ToniRib** [comment]
Think I've also fixed #60 so this should close #60 now.

**Comment by martensonbj** [comment]
Everything looks good! Thanks for the help on the partial, love that the cart now can't be empty if you're making an order. High Five! 👋

**Comment by ToniRib** [comment]
Sounds good, going to merge it in.

**Pull request merged**
