### PR TITLE
Closes #127 Add delete abilities for items to artist and admin

### LINKED ISSUE #127: Artist Removes Item
As a registered artist,
When I visit an item's show page,
And I click on "Delete",
Then I should be brought to my artist index page,
And I shouldn't be able to see the item anymore,
And my item count should have decreased by one

(This should probably also work from the artist's item index. Other artists should not be allowed to delete items that aren't there. The admin should be allowed to delete any item. A user should not be allowed to delete any item.)

### PR DESCRIPTION
**Pull request by Tman22**
[WIP] Added to item show page a button to delete if the current_user is admin or it belongs to the user.

### CODE REVIEW

**Comment by ToniRib** [comment]
Added a negative case test to show an artist can't see the delete button for another artist's item, cleaned up the hound complaints, and added the delete button to the item card partial so it shows up in the index also.

**Comment by ToniRib** [comment]
Just thought of this and checked it out by running on local host, but the delete button doesn't show up for the admin. I'm going to write some tests and try to get that functionality working.

**Comment by Tman22** [comment]
Sweet, thanks for getting to those!

**Comment by martensonbj** [comment]
Helpful addition. We need to fix the lack of image thing so the show page info doesn't kick to the left.

**Pull request merged**
