### PR TITLE
closes #139 cycle through background

### LINKED ISSUE #139: Cycle through background images
Rock some wicked javascript

### PR DESCRIPTION
**Pull request by martensonbj**
Added a rotating background image to the homepage. I have three random images rotating through at the moment just so we can see how the functionality works and had to do some black magic css which might need some heavy refactoring. The carousel uses built in materialize built in jquery calls, and I created a partial for the _home_content (buttons/rough sketch h1) that is embedded in the _slider partial thats then embedded in the index view file. Definitely could be a better way to do this but wanted to experiment. 

I'm also having trouble getting the file path to accessing the background image files that are stored in the assets folder (bg1.jpg etc). I'd imagine I need a link_to image tag but haven't quite gotten there yet.

### CODE REVIEW

**Comment by ToniRib** [comment]
I like it, but the image of the workshop is really, really blurry.

**Comment by ToniRib** [comment]
And maybe this too: http://www.themsv.org/sites/default/files/021015%20portrait%20painter%202.jpg

**Comment by martensonbj** [comment]
Definitely don't mean to keep those images I just wanted to see if the functionality was working. I also don't want the text/buttons to fade in and out so I'm working on that too.

**Comment by ToniRib** [comment]
:+1:

**Comment by ToniRib** [comment]
Since this is now in 136, I think we can close this branch without merging

**Pull request merged**
